sudo: required
services:
  - docker
before_install: 
  - docker build -t chevil/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true chevil/react-test npm test

after_success:
  - docker build -t chevil/multi-client ./client
  - docker build -t chevil/multi-nginx ./nginx
  - docker build -t chevil/multi-server ./server
  - docker build -t chevil/multi-worker ./worker
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  - docker push chevil/multi-client
  - docker push chevil/multi-nginx
  - docker push chevil/multi-server
  - docker push chevil/multi-worker