sudo: required
services:
  - docker
before_install: 
  -docker build -t chevil5/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t chevil5/multi-client ./client
  - docker build -t chevil5/multi-nginx ./nginx
  - docker build -t chevil5/multi-server ./server
  - docker build -t chevil5/multi-worker ./worker
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  - docker push chevil5/multi-client
  - docker push chevil5/multi-nginx
  - docker push chevil5/multi-server
  - docker push chevil5/multi-worker